# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: environment_name
  type: string
- name: environment_conda_yaml
  type: string

steps:
  - task: UsePythonVersion@0
    displayName: 'Setting Python version'
    inputs:
      versionSpec: '3.6'
  - task: Bash@3
    displayName: 'Install Requirements'
    inputs:
      filePath: templates/src/python-sdk/install_requirements.sh
  - task: AzureCLI@2
    displayName: Register environment
    inputs:
      azureSubscription: $(ado_service_connection_aml_ws)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        python templates/src/python-sdk/register_environnment.py -n ${{ parameters.environment_name }} -f ${{ parameters.environment_conda_yaml }}
